language: node_js

env:
  - ENABLE_TESTS=true

node_js:
  - '10'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
- npm run lint
- npm run app:compile
- npm run cover

after_script:
  - echo $TRAVIS_TEST_RESULT
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
