
## Images.Create (object)
+ file: `7d7fi8v41531218345125` (string, required) - ID of the photo on Ackee ImageServer
+ public: `true` (boolean, required) - Whether the photo is public

## Images.Created (object)
+ Include Timestamps
+ mainPhoto (Images.Create, fixed-type)
+ images (array[Images.Create], fixed-type)
