/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/hello": {
    get: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": {
              hello?: string;
              payload?: { [key: string]: unknown };
            };
          };
        };
      };
    };
    post: {
      parameters: {
        header: {
          lang?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": {
              hello?: string;
              payload?: { [key: string]: unknown };
            };
          };
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
          };
        };
      };
    };
  };
}

export interface components {}

export interface operations {}

export interface external {}
